# -*- coding: utf-8 -*-
"""Image Generation with Pre-trained Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SxJp3q3nF0PvBQwBxrV_AYyvAbQCeGMV
"""

!pip install diffusers transformers accelerate torch -q

import torch
from diffusers import StableDiffusionPipeline
import matplotlib.pyplot as plt

model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16
)

pipe = pipe.to("cuda")

prompt = "A fantasy forest with glowing trees"

image = pipe(prompt).images[0]

image.save("generated_image.png")

print("Image Generated Successfully!")

plt.imshow(image)
plt.axis("off")
plt.show()